# docker-compose.yml
version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-20-bullseye
    volumes:
      - ../..:/workspaces:cached
    working_dir: /workspaces/${localWorkspaceFolderBasename}
    command: sleep infinity
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/devdb
      - NODE_ENV=development
    depends_on:
      - db
    ports:
      - "3000:3000"
      - "3001:3001"

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: devdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
